export const category = {
  id: "MENU_WMS_CATEGORY",
  icon: "CategoryIcon",
  text: "Category",
  child: [
    {
      id: "MENU_WMS_CATEGORY.PRODUCT",
      path: "/category/product",
      isPublic: true,
      text: "Product",
      child: [],
    },
    {
      id: "MENU_WMS_CATEGORY.CUSTOMER",
      path: "/category/customer",
      isPublic: true,
      text: "Customer",
      child: [],
    },
    {
      id: "MENU_WMS_CATEGORY.PRODUCT_UNIT",
      path: "/category/unit-product",
      isPublic: true,
      text: "Product Unit",
      child: [],
    },
    {
      id: "MENU_WMS_CATEGORY.PRODUCT_CATEGORY",
      path: "/category/category-product",
      isPublic: true,
      text: "Product Category",
      child: [],
    },
    {
      id: "MENU_WMS_CATEGORY.DISTRIBUTING_CHANNEL",
      path: "/category/distributing-channel",
      isPublic: true,
      text: "Distribution Channel",
      child: [],
    },
    {
      id: "MENU_WMS_CATEGORY.CUSTOMER_TYPE",
      path: "/category/type-customer",
      isPublic: true,
      text: "Customer Type",
      child: [],
    },
    {
      id: "MENU_WMS_CATEGORY.CONTRACT_TYPE",
      path: "/category/type-contract",
      isPublic: true,
      text: "Contract Type",
      child: [],
    },
  ],
};
