create table time_table(
	cid int not null ,
	acid int not null ,
	semester_id int2 not null,
	course_code varchar(7) ,
	course_name text ,
	capacity varchar(20) ,
	note text ,
	course_week varchar(25) ,
	day_of_week int ,
	course_time varchar(10) ,
	start_section int ,
	finish_section int ,
	shift varchar(6) ,
	room varchar(10) ,
	type_of_class varchar(8) ,
	total int ,
	course_session int ,
	state varchar(20),
	experiment varchar(2),
	mid int ,
	college varchar(15) ,
	course_period varchar(2) ,
	constraint pk_schedule primary key (CID,ACID)
)
