CREATE TABLE facilities
(
    facility_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code            VARCHAR(255),
    name            VARCHAR(255),
    facility_width  INTEGER ,
    facility_lenght INTEGER ,
    address         VARCHAR(255),
    update_at       TIMESTAMP WITHOUT TIME ZONE,
    create_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_facilities PRIMARY KEY (facility_id)
);
CREATE TABLE shelves
(
    shelf_id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    facility_id INTEGER,
    x           INTEGER,
    y           INTEGER,
    width       INTEGER,
    lenght      INTEGER,
    status      VARCHAR(255),
    num         INTEGER,
    update_at   TIMESTAMP WITHOUT TIME ZONE,
    create_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_shelves PRIMARY KEY (shelf_id)
);
CREATE TABLE products
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(255),
    type        VARCHAR(255),
    name        VARCHAR(255),
    description VARCHAR(255),
    image       VARCHAR(255),
    is_active   BOOLEAN,
    opt1        VARCHAR(255),
    opt2        VARCHAR(255),
    opt3        VARCHAR(255),
    update_at   TIMESTAMP WITHOUT TIME ZONE,
    create_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_products PRIMARY KEY (id)
);
CREATE TABLE variants
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id   INTEGER                                  NOT NULL,
    name         VARCHAR(255),
    sku          VARCHAR(255),
    is_active    BOOLEAN,
    image        VARCHAR(255),
    weight_unit  VARCHAR(255),
    weight_value INTEGER,
    import_price DECIMAL,
    whole_price  DECIMAL,
    retail_price DECIMAL,
    on_hand      DECIMAL,
    available    DECIMAL,
    opt1         VARCHAR(255),
    opt2         VARCHAR(255),
    opt3         VARCHAR(255),
    update_at    TIMESTAMP WITHOUT TIME ZONE,
    create_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_variants PRIMARY KEY (id)
);


CREATE TABLE import_order
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(255),
    total       DECIMAL,
    facility_id INTEGER,
    status      VARCHAR(255),
    update_at   TIMESTAMP WITHOUT TIME ZONE,
    create_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_import_order PRIMARY KEY (id)
);

CREATE TABLE import_line_item
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    variant_id       INTEGER,
    name             VARCHAR(255),
    quantity         DECIMAL,
    import_price     DECIMAL,
    whole_price      DECIMAL,
    retail_price     DECIMAL,
    import_id        INTEGER                                  NOT NULL,
    current_quantity DECIMAL,
    status           VARCHAR(255),
    total            DECIMAL,
    on_hand          DECIMAL,
    available        DECIMAL,
    image            VARCHAR(255),
    sku              VARCHAR(255),
    update_at        TIMESTAMP WITHOUT TIME ZONE,
    create_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_import_line_item PRIMARY KEY (id)
);

CREATE TABLE shelf_variants
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    shelf_id     INTEGER,
    variant_id   INTEGER,
    line_item_id INTEGER,
    quantity     DECIMAL,
    update_at    TIMESTAMP WITHOUT TIME ZONE,
    create_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_shelf_variants PRIMARY KEY (id)
);

CREATE TABLE lots_date
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code           VARCHAR(255),
    variant_id     INTEGER,
    quantity       DECIMAL,
    manufacture_at TIMESTAMP WITHOUT TIME ZONE,
    expiration_at  TIMESTAMP WITHOUT TIME ZONE,
    update_at      TIMESTAMP WITHOUT TIME ZONE,
    create_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_lots_date PRIMARY KEY (id)
);

CREATE TABLE export_order
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(255),
    total       DECIMAL,
    facility_id INTEGER,
    status      VARCHAR(255),
    update_at   TIMESTAMP WITHOUT TIME ZONE,
    create_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_export_order PRIMARY KEY (id)
);

CREATE TABLE export_shelf_variant
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    shelf_variant_id    INTEGER,
    export_line_item_id INTEGER,
    quantity            DECIMAL,
    exported            BOOLEAN,
    update_at           TIMESTAMP WITHOUT TIME ZONE,
    create_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_export_shelf_variant PRIMARY KEY (id)
);

CREATE TABLE export_line_item
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    variant_id     INTEGER,
    quantity       DECIMAL,
    total_quantity DECIMAL,
    price          DECIMAL,
    export_id      INTEGER                                  NOT NULL,
    total          DECIMAL,
    update_at      TIMESTAMP WITHOUT TIME ZONE,
    create_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_export_line_item PRIMARY KEY (id)
);
