SERVICE_HOST: localhost
SERVICE_PORT: 8080
DOCKER_SERVER_HOST: http://erp3.soict.ai:12375
SQL_DB_HOST: erp3.soict.ai
SQL_DB_PORT: 6543
SQL_DB_USER: postgres
SQL_DB_PASS: "0penerp@2023#"
POSTGRES_DB: erp_dev_2024

google.api_key: 'AIzaSyDWbACfGeZnCaYNOMXDDqzxm4HsqSQLSJg'

server:
  port: 8080
  servlet:
    context-path: '/api'
  compression:
    enabled: true # Enable response compression
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # The comma-separated list of mime types that should be compressed
    min-response-size: 2048 # Compress the response only if the response size is at least 2 KB

rabbit:
  CONCURRENT_CONSUMERS: 5
  MAX_CONCURRENT_CONSUMERS: 8
  PREFETCH_COUNT: 1
  RETRY_LIMIT: 2
  DEAD_MESSAGE_TTL: 120000

app:
  cors:
    allowed-origins: http://localhost:3000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://erp3.soict.ai/iam/realms/OpenERP-Dev/protocol/openid-connect/certs
  jmx:
    enabled: false
  rabbitmq: # RabbitMQ properties
    addresses: erp.soict.ai:5672,erp2.soict.ai:5672,erp3.soict.ai:5672
    username: tuanla
    password: 73d68b2d97050cce0fdc3f82288594d95685c95e700cb5544d5f1b58654505e2b498e2f01d1aa4e0810c20adea7f1afbcf0bc70b0801a9895ce55f4ec19949a2
    virtual_host: openerp.dev
    programming_contest:
      concurrent_consumers: 4
      max_concurrent_consumers: 4
      prefetch_count: 1
      retry_limit: 2
      dead_message_ttl: 120000
    listener:
      simple:
        auto-startup: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password:
    expiretime: 12
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    throw-exception-if-no-handler-found: true
  data:
    redis:
      repositories:
        enabled: false
    rest:
      #base-path: /rest
      detection-strategy: ANNOTATED
    mongodb:
      uri: mongodb://localhost:27017,localhost:27018,localhost:27019
      replicaSet: rs0
      database: baseweb
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SQL_DB_HOST}:${SQL_DB_PORT}/${POSTGRES_DB}
    username: ${SQL_DB_USER}
    password: ${SQL_DB_PASS}
    hikari: # reference: https://github:com/brettwooldridge/HikariCP#configuration-knobs-baby:
      maxLifetime: 30000
      leakDetectionThreshold: 30000
  jpa:
    properties:
      hibernate:
        format_sql: true # not recommended for production
        order_inserts: true
        jdbc:
          batch_size: 50
        ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: anhtuan0126104@gmail.com
    password: prmsathjqufwtxxw
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true

logging:
  level:
    root: INFO
    org:
      springframework: INFO
      springframework.security: TRACE
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

#      hibernate:
#       SQL: DEBUG
#       type:
#         descriptor:
#           sql:
#             BasicBinder: TRACE
content:
  fs:
    filesystemRoot: C:\DungPQ\project\openerp-microservices\openerp-micro-service\lms\lmsbackend\baseweb
    videoPath: videos/
    classManagementDataPath: src/main/java/com/hust/baseweb/applications/education/classmanagement/data/
    programSubmissionDataPath: src/main/java/com/hust/baseweb/applications/education/programsubmisson/data/
    backlogDataPath: src/main/java/com/hust/baseweb/applications/backlog/data/

content-repo:
  url: 'http://localhost:8080/'

postsys:
  post_assign_delay: 500000000
