export const SOCKET_EVENTS = {
  CONNECTION: "connection",
  DISCONNECTED: "disconnected",
  LEAVE_ROOM: "leave_room",
  CONNECT_TO_EDITOR: "connect-to-editor",
  SEND_CODE_CHANGES: "send-code-changes",
  RECEIVE_CODE_CHANGES: "receive-code-changes",
  JOINED: "joined",
  UPDATE_USER_PERMISSION: "update-user-permission",
  REFRESH_USER_PERMISSION: "refresh-user-permission",
  UPDATE_ROOM_PERMISSION: "update-room-permission",
  REFRESH_ROOM_PERMISSION: "refresh-room-permission",
  DELETE_USER_PERMISSION: "delete-user-permission",
  REFRESH_DELETE_PERMISSION: "refresh-delete-permission",
  REQUEST_ON_OFF_MIC: "request-on-off-mic",
  ACCEPT_ON_OFF_MIC: "accept-on-off-mic",
};

export const PROGRAMMING_LANGUAGES = {
  CPP: {
    label: "C++",
    value: "CPP",
  },
  JAVA: {
    label: "Java",
    value: "JAVA",
  },
  PYTHON: {
    label: "Python",
    value: "PYTHON",
  },
};

export const CHARACTER_COLOR = {
  A: "#FF0000",
  B: "#FFA500",
  C: "#FFFF00",
  D: "#008000",
  E: "#0000FF",
  F: "#800080",
  G: "#FFC0CB",
  H: "#FFD700",
  I: "#00FFFF",
  J: "#FF69B4",
  K: "#8B4513",
  L: "#9400D3",
  M: "#FF8C00",
  N: "#00FF00",
  O: "#808080",
  P: "#FF00FF",
  Q: "#B0C4DE",
  R: "#1E90FF",
  S: "#FF6347",
  T: "#008080",
  U: "#9370DB",
  V: "#7CFC00",
  W: "#00FF7F",
  X: "#FF1493",
  Y: "#FFFFF0",
  Z: "#DC143C",
};
