export const API_PATH = {
  WAREHOUSE: "/wmsv2/admin/warehouse",
  WAREHOUSE_DETAIL: "/wmsv2/admin/warehouse/detail",
  PRODUCT_WAREHOUSE: "/wmsv2/admin/warehouse/product",
  PRODUCT: "/wmsv2/admin/product",
  PRODUCT_CATEGORY: "/wmsv2/admin/product/category",
  PRODUCT_PRICE: "/wmsv2/admin/product/price-config",
  RECEIPT: "/wmsv2/admin/receipt",
  CART: "/wmsv2/customer/cart",
  CUSTOMER_SALE_ORDER: "/wmsv2/customer/cart/create-order",
  ADMIN_SALE_ORDER: "/wmsv2/admin/order",
  APPROVE_SALE_ORDER: "/wmsv2/admin/order/approve",
  CANCEL_SALE_ORDER: "/wmsv2/admin/order/cancel",
  SALE_MANAGEMENT_RECEIPT_REQUEST: "/wmsv2/sale-management/receipt",
  SALE_MANAGEMENT_RECEIPT_REQUEST_APPROVAL_LISTING: "/wmsv2/sale-management/receipt/approval-listing",
  APPROVE_RECEIPT_REQUEST: "/wmsv2/sale-management/receipt/approve",
  CANCEL_RECEIPT_REQUEST: "/wmsv2/sale-management/receipt/cancel",
  PROCESS_RECEIPT_REQUEST: "/wmsv2/process/receipt-request",
  DELIVERY_MANAGER_DELIVERY_PERSON: "/wmsv2/delivery-manager/delivery-person",
  WAREHOUSE_DETAIL_WITH_PRODUCT: "/wmsv2/admin/warehouse/detail-with-products",
  ASSIGN_ORDER_ITEM: "/wmsv2/admin/order/assign-order-item"
}