app:
  name: demo-app
  version: 1.0.0

server:
  port: 8080

# change_me
keycloak:
  realm: stack
  auth-server-url: http://localhost:8082
  credentials:
    client-id: admin-client
    client-secret: zbmcNOm0CgymvWU0iW69TeziMiTAffNa
