export const teachingassignment = {
  id: "MENU_EDUCATION_TEACHING_ASSIGNMENT",
  path: "/edu/teaching-assignment",
  isPublic: false,
  icon: "Schedule",
  text: "Phân công giảng dạy",
  child: [
    // {
    //   id: "MENU_EDUCATION_VIEW_LIST_SEMESTER",
    //   path: "/edu/semester",
    //   isPublic: false,
    //   icon: "StarBorder",
    //   text: "Học kì",
    //   child: [],
    // },
    {
      id: "MENU_EDUCATION_VIEW_LIST_COURSE",
      path: "/edu/teaching-assignment/courses",
      isPublic: false,
      icon: "StarBorder",
      text: "Học phần",
      child: [],
    },
    // {
    //   id: "MENU_EDUCATION_VIEW_LIST_TEACHER",
    //   path: "/edu/teachers/list",
    //   isPublic: false,
    //   icon: "StarBorder",
    //   text: "Giảng viên",
    //   child: [],
    // },
    // {
    //   id: "MENU_EDUCATION_VIEW_LIST_CLASS",
    //   path: "/edu/classes-list",
    //   isPublic: false,
    //   icon: "StarBorder",
    //   text: "Lớp",
    //   child: [],
    // },
    {
      id: "MENU_EDUCATION_VIEW_LIST_ASSIGNMENT",
      path: "/edu/teaching-assignment/plan",
      isPublic: false,
      icon: "StarBorder",
      text: "Kế hoạch phân công",
      child: [],
    },
  ],
};
