export const scheduleInformation = {
    id: "MENU_SCHEDULE_INFORMATION",
    icon: "InfoIcon",
    text: "Schedule Information",
    child: [
      {
        id: "MENU_SCHEDULE_INFORMATION.CLASS_CODE",
        path: "/schedule-information/class-code",
        isPublic: true,
        text: "Class Code",
        child: [],
      },
      {
        id: "MENU_SCHEDULE_INFORMATION.CLASSROOM",
        path: "/schedule-information/classroom",
        isPublic: true,
        text: "Classroom",
        child: [],
      },
      {
        id: "MENU_SCHEDULE_INFORMATION.SEMESTER",
        path: "/schedule-information/semester",
        isPublic: true,
        text: "Semester",
        child: [],
      },
      {
        id: "MENU_SCHEDULE_INFORMATION.INSTITUTE",
        path: "/schedule-information/institute",
        isPublic: true,
        text: "Institute",
        child: [],
      },
      {
        id: "MENU_SCHEDULE_INFORMATION.MODULE",
        path: "/schedule-information/module",
        isPublic: true,
        text: "Module",
        child: [],
      },
      {
        id: "MENU_SCHEDULE_INFORMATION.CLASSTYPE",
        path: "/schedule-information/class-type",
        isPublic: true,
        text: "Class Type",
        child: [],
      },
      {
        id: "MENU_SCHEDULE_INFORMATION.MANAGEMENTCODE",
        path: "/schedule-information/management-code",
        isPublic: true,
        text: "Management Code",
        child: [],
      },
      {
        id: "MENU_SCHEDULE_INFORMATION.OPENBATCH",
        path: "/schedule-information/open-batch",
        isPublic: true,
        text: "Open Batch",
        child: [],
      },
      {
        id: "MENU_SCHEDULE_INFORMATION.STATE",
        path: "/schedule-information/state",
        isPublic: true,
        text: "State",
        child: [],
      },
      {
        id: "MENU_SCHEDULE_INFORMATION.STUDYTIME",
        path: "/schedule-information/study-time",
        isPublic: true,
        text: "Study Time",
        child: [],
      },
      {
        id: "MENU_SCHEDULE_INFORMATION.STUDYWEEK",
        path: "/schedule-information/study-week",
        isPublic: true,
        text: "Study Week",
        child: [],
      },
      {
        id: "MENU_SCHEDULE_INFORMATION.WEEKDAY",
        path: "/schedule-information/week-day",
        isPublic: true,
        text: "Week Day",
        child: [],
      }
    ],
  };