global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

#  - job_name: "prometheus"
#    static_configs:
#      - targets: [ "localhost:9090" ]
#
  - job_name: 'api'
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'api:8080' ]

  - job_name: 'consumer'
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'consumer:8082' ]