export const eduLearningManagement = {
  id: "MENU_EDUCATION_LEARNING_MANAGEMENT_STUDENT",
  path: "",
  isPublic: false,
  icon: "LocalLibraryIcon",
  text: "Learning",
  child: [
    {
      id: "MENU_EDUCATION_LEARNING_MANAGEMENT_STUDENT_REGISTER_CLASS",
      path: "/edu/class/register",
      isPublic: false,
      icon: null,
      text: "Class Registration",
      child: [],
    },
    {
      id: "MENU_EDUCATION_LEARNING_MANAGEMENT_STUDENT_VIEW_LIST_CLASS",
      path: "/edu/student/class/list",
      isPublic: false,
      icon: null,
      text: "Classes",
      child: [],
    },
    {
      id: "MENU_EDUCATION_TEACHING_MANAGEMENT_STUDENT_QUIZ_TEST_LIST",
      path: "/edu/class/student/quiztest/list",
      isPublic: false,
      icon: null,
      text: "Join Quiz Test",
      child: [],
    },
    {
      id: "MENU_EDUCATION_TEACHING_MANAGEMENT_STUDENT_MY_QUIZ_TEST_LIST",
      path: "/edu/class/student/myquiztest/list",
      isPublic: false,
      icon: null,
      text: "My Quiz Test",
      child: [],
    },

    {
      id: "MENU_EDUCATION_THESIS_DEFENSE_JURY_STUDENT_MANAGEMENT",
      path: "/edu/student/thesis/create",
      isPublic: true,
      icon: null,
      text: "Create Thesis",
      child: [],
    },
  ],
};
